apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lms-db
  template:
    metadata:
      labels:
        app: lms-db
    spec:
      containers:
        - name: postgres
          image: postgres:13
          ports:
            - containerPort: 5432
          environment:
            - name: POSTGRES_DB
              value: "lmsdb"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
---
apiVersion: v1
kind: Service
metadata:
  name: lms-db-service
spec:
  selector:
    app: lms-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
