apiVersion: v1
kind: Service
metadata:
  name: lms-app-service
spec:
  selector:
    app: lms-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer  # Use NodePort or ClusterIP if not using a cloud provider
